[package]
name = "puniyu_node_protocol"
version = "0.2.6"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
serde.workspace = true
napi-derive.workspace = true
napi = { workspace = true, features = ["chrono_date"] }
prost = { version = "0.14.1" }

puniyu_types = { git = "https://github.com/puniyu/puniyu", rev = "e240974" }
puniyu_protocol = { git = "https://github.com/puniyu/puniyu", rev = "e240974" }
chrono = "0.4.42"


[build-dependencies]
napi-build.workspace = true



